In [2]:
import numpy as np
import pandas as pd

### Question 1 — Load & Look
Load `healthcare_dataset.csv` into a DataFrame called `df`. Display the first 5 rows and print the shape (rows, columns).

In [3]:
df=pd.read_csv("healthcare_dataset.csv")

In [4]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
df.shape

(55500, 15)

### Question 2 — Get to Know the Data
Check the data type of every column using `.dtypes`, and count how many missing values each column has using `.isnull().sum()`.

In [6]:
df.dtypes

Name                      str
Age                     int64
Gender                    str
Blood Type                str
Medical Condition         str
Date of Admission         str
Doctor                    str
Hospital                  str
Insurance Provider        str
Billing Amount        float64
Room Number             int64
Admission Type            str
Discharge Date            str
Medication                str
Test Results              str
dtype: object

In [7]:
df.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

### Question 3 — Unique Values
Find how many unique values are in the `Medical Condition` column, and print out what those unique values actually are.

In [9]:
df['Medical Condition'].nunique()

6

In [10]:
df['Medical Condition'].unique()

<StringArray>
['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension', 'Arthritis']
Length: 6, dtype: str

### Question 4 — Selecting Columns
Create a new DataFrame called `patients` that contains only these columns: `Name`, `Age`, `Medical Condition`, and `Billing Amount`.

In [11]:
patients=df[['Name','Age','Medical Condition','Billing Amount']]

In [12]:
patients

                    Name  Age Medical Condition  Billing Amount
0          Bobby JacksOn   30            Cancer    18856.281306
1           LesLie TErRy   62           Obesity    33643.327287
2            DaNnY sMitH   76           Obesity    27955.096079
3           andrEw waTtS   28          Diabetes    37909.782410
4          adrIENNE bEll   43            Cancer    14238.317814
...                  ...  ...               ...             ...
55495  eLIZABeTH jaCkSOn   42            Asthma     2650.714952
55496         KYle pEREz   61           Obesity    31457.797307
55497       HEATher WaNG   38      Hypertension    27620.764717
55498     JENniFER JOneS   43         Arthritis    32451.092358
55499       jAMES GARCiA   53         Arthritis     4010.134172

[55500 rows x 4 columns]

### Question 5 — Boolean Filtering
Filter the dataset to show only patients where `Medical Condition` is `"Diabetes"` **and** `Age` is greater than 50.

In [13]:
df['Medical Condition']=="Diabetes"

0        False
1        False
2        False
3         True
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Name: Medical Condition, Length: 55500, dtype: bool

In [14]:
df['Age']>50

0        False
1         True
2         True
3        False
4        False
         ...
55495    False
55496     True
55497    False
55498    False
55499     True
Name: Age, Length: 55500, dtype: bool

In [15]:
(df['Medical Condition']=="Diabetes")&(df['Age']>50)

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Length: 55500, dtype: bool

In [16]:
df[(df['Medical Condition']=="Diabetes")&(df['Age']>50)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal
66,ChRiStOPhER gOnzAlez,59,Male,B+,Diabetes,2019-11-21,Patricia Dunn,Rhodes-Carey,Medicare,10107.187651,368,Emergency,2019-12-08,Penicillin,Abnormal
82,SeaN jenniNGs,80,Female,AB-,Diabetes,2023-11-12,James Tucker,Clark-Johnson,Blue Cross,20257.544283,255,Elective,2023-12-12,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55409,WEslEY BarkEr,58,Male,O+,Diabetes,2020-06-22,Jonathan Cabrera,Long LLC,Cigna,44241.630103,324,Urgent,2020-07-05,Ibuprofen,Normal
55416,GrEG Bush,67,Male,B-,Diabetes,2021-09-26,Joshua Davis,Ltd Cox,Cigna,16097.163523,483,Emergency,2021-10-12,Paracetamol,Abnormal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,UnitedHealthcare,5271.154491,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959.491185,462,Urgent,2019-12-06,Lipitor,Abnormal
55439,cHRiStINE MCCARty,75,Male,AB+,Diabetes,2024-04-28,Gregory Pineda,Wu-Stark,Aetna,23720.022368,313,Emergency,2024-05-19,Penicillin,Abnormal

### Question 6 — Cleaning: Duplicates & Bad Values
This dataset has some issues hiding in it:
1. Remove exact duplicate rows using `drop_duplicates()`.
2. Some rows have a **negative** `Billing Amount`, which doesn't make sense for a hospital bill. Remove any rows where `Billing Amount` is less than 0.

Print the number of rows before and after, so you can see how many were removed.

In [17]:
df.shape

(55500, 15)

In [18]:
df=df.drop_duplicates()

In [19]:
df.shape

(54966, 15)

In [20]:
df['Billing Amount']<0

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Name: Billing Amount, Length: 54966, dtype: bool

In [21]:
df['Billing Amount']>=0

0        True
1        True
2        True
3        True
4        True
         ...
55495    True
55496    True
55497    True
55498    True
55499    True
Name: Billing Amount, Length: 54966, dtype: bool

In [22]:
df[df['Billing Amount']>=0]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [23]:
df=df[df['Billing Amount']>=0]

In [24]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

### Question 7 — Cleaning: Inconsistent Text
Look closely at the `Name` column — the capitalization is inconsistent (e.g. `"Bobby JacksOn"`, `"LesLie TErRy"`). Clean it so every name is properly title-cased (e.g. `"Bobby Jackson"`).

In [25]:
df['Name'].head()

0    Bobby JacksOn
1     LesLie TErRy
2      DaNnY sMitH
3     andrEw waTtS
4    adrIENNE bEll
Name: Name, dtype: str

In [26]:
df['Name'].str.title()

0            Bobby Jackson
1             Leslie Terry
2              Danny Smith
3             Andrew Watts
4            Adrienne Bell
               ...
55495    Elizabeth Jackson
55496           Kyle Perez
55497         Heather Wang
55498       Jennifer Jones
55499         James Garcia
Name: Name, Length: 54860, dtype: str

In [27]:
df['Name']=df['Name'].str.title()

In [28]:
df['Name'].head()

0    Bobby Jackson
1     Leslie Terry
2      Danny Smith
3     Andrew Watts
4    Adrienne Bell
Name: Name, dtype: str

### Question 8 — Feature Engineering with Dates
Convert `Date of Admission` and `Discharge Date` into real datetime columns using `pd.to_datetime()`. Then create a new column called `Length of Stay` that stores the number of days between admission and discharge for each patient.

In [29]:
df['Date of Admission'].dtype

In [30]:
pd.to_datetime(df['Date of Admission'])

0       2024-01-31
1       2019-08-20
2       2022-09-22
3       2020-11-18
4       2022-09-19
           ...
55495   2020-08-16
55496   2020-01-23
55497   2020-07-13
55498   2019-05-25
55499   2024-04-02
Name: Date of Admission, Length: 54860, dtype: datetime64[us]

In [31]:
pd.to_datetime(df['Date of Admission']).dtype

dtype('<M8[us]')

In [32]:
df['Date of Admission']=pd.to_datetime(df['Date of Admission'])

In [33]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [34]:
df['Discharge Date']=pd.to_datetime(df['Discharge Date'])

In [35]:
df['Discharge Date'].dtype

dtype('<M8[us]')

In [36]:
df['Discharge Date']-df['Date of Admission']

0        2 days
1        6 days
2       15 days
3       30 days
4       20 days
          ...
55495   30 days
55496    9 days
55497   28 days
55498    6 days
55499   27 days
Length: 54860, dtype: timedelta64[us]

In [37]:
(df['Discharge Date']-df['Date of Admission']).dt.days

0         2
1         6
2        15
3        30
4        20
         ..
55495    30
55496     9
55497    28
55498     6
55499    27
Length: 54860, dtype: int64

In [38]:
df['Length of Stay']=(df['Discharge Date']-df['Date of Admission']).dt.days

In [39]:
display(df.head())

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20

### Question 9 — apply() with a Custom Function
Write a function called `get_age_group(age)` that returns:
- `"Child"` if age is 12 or under
- `"Teen"` if age is between 13 and 19
- `"Adult"` if age is between 20 and 59
- `"Senior"` if age is 60 or above

Then use `.apply()` to create a new column `Age Group` in `df` using this function.

In [40]:
def get_age_group(age):
    if age<=12:
        return "Child"
    elif age>12 and age<=19:
        return "Teen"
    elif age>19 and age<=59:
        return "Adult"
    else:
        return "Senior"

In [41]:
df['Age Group']=df['Age'].apply(get_age_group)

In [42]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,Adult
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Senior
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,Senior
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Adult
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult

### Question 10 — apply() with a Lambda
Using `.apply()` with a **lambda function**, create a new column called `High Bill` that stores `"Yes"` if a patient's `Billing Amount` is above the *average* billing amount of the whole dataset, and `"No"` otherwise.

In [43]:
average_bill=df['Billing Amount'].mean()

In [44]:
df['High Bill']=df['Billing Amount'].apply(lambda x : "Yes" if x>average_bill else "No")

In [45]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group,High Bill
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,Adult,No
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Senior,Yes
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,Senior,Yes
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Adult,Yes
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult,No

### Question 11 — Sorting
Sort the dataset by `Billing Amount` in descending order, and display the top 10 most expensive cases — just the `Name`, `Medical Condition`, and `Billing Amount` columns.

In [46]:
ten_cases=df.sort_values(by="Billing Amount", ascending=False).head(10)

In [47]:
ten_cases

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group,High Bill
36349,Todd Carrillo,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764.276736,209,Elective,2023-10-04,Ibuprofen,Normal,26,Adult,Yes
51313,Karen Kline,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive,14,Senior,Yes
34613,Karen Kline,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive,14,Senior,Yes
5735,David Sandoval,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52271.663747,228,Emergency,2019-11-11,Ibuprofen,Normal,9,Adult,Yes
7088,Kathryn Gonzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52211.852966,383,Urgent,2020-08-12,Paracetamol,Inconclusive,1,Teen,Yes
1574,Brett Marshall,42,Female,B+,Asthma,2021-11-10,Robert Hartman,PLC Garner,Aetna,52181.837792,140,Emergency,2021-11-17,Penicillin,Inconclusive,7,Adult,Yes
52826,Laurie Hood,43,Female,A-,Arthritis,2021-06-27,Brian Riley,Walker-Garcia,Cigna,52170.036854,306,Urgent,2021-06-29,Penicillin,Normal,2,Adult,Yes
6663,Laurie Hood,42,Female,A-,Arthritis,2021-06-27,Brian Riley,Walker-Garcia,Cigna,52170.036854,306,Urgent,2021-06-29,Penicillin,Normal,2,Adult,Yes
33117,Justin Clark,53,Female,AB+,Cancer,2019-05-30,Andrea Jones,Ruiz-Anthony,UnitedHealthcare,52154.237722,399,Urgent,2019-06-22,Aspirin,Normal,23,Adult,Yes
34368,Scott Powell,38,Female,B+,Cancer,2019-05-20,Stephen Hood PhD,George-Gonzalez,Cigna,52102.240889,155,Emergency,2019-05-29,Ibuprofen,Normal,9,Adult,Yes

In [48]:
ten_cases[['Name','Medical Condition','Billing Amount']]

                   Name Medical Condition  Billing Amount
36349     Todd Carrillo      Hypertension    52764.276736
51313       Karen Kline            Cancer    52373.032374
34613       Karen Kline            Cancer    52373.032374
5735     David Sandoval      Hypertension    52271.663747
7088   Kathryn Gonzales          Diabetes    52211.852966
1574     Brett Marshall            Asthma    52181.837792
52826       Laurie Hood         Arthritis    52170.036854
6663        Laurie Hood         Arthritis    52170.036854
33117      Justin Clark            Cancer    52154.237722
34368      Scott Powell            Cancer    52102.240889

### Question 12 — GroupBy & Aggregation
Group the data by `Medical Condition` and find the **average** `Billing Amount` and the **average** `Length of Stay` (from Question 8) for each condition.

Based on your result: which medical condition has the highest average billing amount?

In [49]:
df.groupby('Medical Condition').agg(
    average_billing_amount=("Billing Amount","mean"),
    average_stay=("Length of Stay","mean")
)

                   average_billing_amount  average_stay
Medical Condition
Arthritis                    25542.898356     15.503747
Asthma                       25685.385020     15.676104
Cancer                       25205.924207     15.510141
Diabetes                     25714.326349     15.429488
Hypertension                 25559.844868     15.435440
Obesity                      25859.215373     15.439465