## Country Analysis using Pandas

#### Exploring real-world dataset operations using Pandas

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Countries.csv")

In [3]:
df.head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    str
 1   country_long                             194 non-null    str
 2   currency                                 194 non-null    str
 3   capital_city                             194 non-null    str
 4   region                                   194 non-null    str
 5   continent                                194 non-null    str
 6   demonym                                  194 non-null    str
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    str
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    str
 63  title                                    187 non-null    str
dtypes: float64(48), int64(6), str(10)
memory usage: 97.1 KB

### Finding the country with the maximum population

In [6]:
max_population=df['population'].max()

In [8]:
df[df['population']==max_population]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [9]:
df[df['population']==df['population'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [15]:
df[df['population']==df['population'].max()]['country']

75    India
Name: country, dtype: str

#### Finding the capital of the country with the maximum population

In [14]:
df[df['population']==df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: str

### Finding the country with the minimum population

In [10]:
df['population'].min()

np.int64(11312)

In [12]:
df[df['population']==df['population'].min()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.0,178.0,18.0,...,11312,6.25,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister

In [16]:
df[df['population']==df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: str

#### Finding the capital city of the country with the minimum population

In [17]:
df[df['population']==df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: str

### Finding the country with the maximum democracy score

In [ ]:
df.sort_values(by='democracy_score',ascending=False)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.00,10.0,9859.62,...,5457127,44.97040,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.00,-18.0,18720.00,...,381900,47.61900,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.00,15.0,30055.40,...,10486941,46.41830,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.00,174.0,101540.00,...,5124100,50.42020,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.00,10.0,26199.90,...,5903037,43.57540,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,South Sudan,Republic of South Sudan,South Sudanese Pound,Juba,Middle Africa,Africa,South Sudanese,7.00,30.0,282510.00,...,10913164,32.36360,8638206,2274958,1.71,0.00,Unknown,12.5,Salva Kiir Mayardit,President
174,Tonga,Kingdom of Tonga,Tongan pa'anga,Nuku'alofa,Polynesia,Oceania,Tongan,-20.00,-175.0,350.00,...,106858,3.70370,82147,24711,3.08,0.00,Unknown,17.9,Pōhiva Tu'i'onetoa,Prime Minister
170,The Bahamas,Commonwealth of The Bahamas,Bahamian dollar,Nassau,Caribbean,Americas,Bahamian,24.25,-76.0,140.00,...,409984,17.94870,67680,342304,0.00,0.00,Unknown,28.9,Hubert Minnis,Prime Minister
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.00,178.0,18.00,...,11312,6.25000,3900,7412,0.00,0.00,Unknown,21.0,Kausea Natano,Prime Minister
187,Vanuatu,Republic of Vanuatu,Vanuatu vatu,Port Vila,Melanesia,Oceania,Ni-Vanuatu,-16.00,167.0,1870.00,...,326740,1.92308,242389,84351,0.00,0.00,Unknown,15.6,Charlot Salwai,Prime Minister

#### Top 5 countries with the maximum democracy score

In [23]:
df.sort_values(by='democracy_score',ascending=False).head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [22]:
df.sort_values(by='democracy_score',ascending=False).head(5)['country']

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: str

In [13]:
df['democracy_score'].head(5)

0    2.97
1    5.98
2    3.50
3    0.00
4    3.62
Name: democracy_score, dtype: float64

### Finding the number of regions by using value counts

In [18]:
df['region'].value_counts()

region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [27]:
total_regions=df['region'].value_counts().count()
print(total_regions)

22

### Finding all countries in eastern european region

In [28]:
df['region']=="Eastern Europe"

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190    False
191    False
192    False
193    False
Name: region, Length: 194, dtype: bool

In [29]:
df[df['region']=="Eastern Europe"]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.0,82810.0,...,9208701,40.0000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.0,50470.0,...,6465097,24.1667,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.5,35238.7,...,10526073,25.5000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.0,49030.0,...,9683505,14.0704,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister
111,Moldova,Republic of Moldova,Moldovan leu,Chișinău,Eastern Europe,Europe,Moldovan,47.000000,29.0,22646.0,...,2592477,40.5941,1473227,1119250,2.51,5.85,Hybrid regime,31.2,Ion Chicu,Prime Minister
136,Poland,Republic of Poland,Polish zloty,Warsaw,Eastern Europe,Europe,Polish,52.000000,20.0,144610.0,...,37561599,28.2609,14974307,22587292,2.71,6.67,Flawed democracy,36.3,Mateusz Morawiecki,Prime Minister
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.0,135910.0,...,18956666,19.0909,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.000000,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.5,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.0,413110.0,...,38000000,20.3310,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President

In [31]:
df[df['region']=="Eastern Europe"]['country']

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: str

In [33]:
eastern_european_countries=df[df['region']=="Eastern Europe"]['country'].count()
print(eastern_european_countries)

10

### Finding the political leader of the 2nd most populous country

In [41]:
df.sort_values(by='population',ascending=False).iloc[1]['political_leader']

'Xi Jinping'

### Finding all countries without a political leader

In [54]:
df['political_leader'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190     True
191    False
192    False
193    False
Name: political_leader, Length: 194, dtype: bool

In [55]:
df[df['political_leader'].isnull()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.500000,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.0,...,47657,31.2500,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.0,...,103948,18.1818,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
172,Timor-Leste,Democratic Republic of Timor-Leste,U.S. dollar,Dili,South-Eastern Asia,Asia,East Timorese,-8.833333,125.916667,3414.0,...,1341296,40.0000,911089,430207,2.61,7.19,Flawed democracy,16.7,NaN,NaN
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN

In [59]:
df[df['political_leader'].isnull()]['country'].count()

np.int64(7)

### Finding all countries which have ***Republic*** in the name

In [68]:
def check_republic(txt):
    txt=txt.lower()
    if 'republic' in txt:
        return True
    return False

In [70]:
check_republic(" People's Republic of Angola")

True

In [69]:
check_republic("Islamic State of Afghanistan")

False

In [61]:
df['country_long']

0                 Islamic State of Afghanistan
1                          Republic of Albania
2      People's Democratic Republic of Algeria
3                      Principality of Andorra
4                  People's Republic of Angola
                        ...
189              Socialist Republic of Vietnam
190                         West Bank and Gaza
191                          Republic of Yemen
192                         Republic of Zambia
193                       Republic of Zimbabwe
Name: country_long, Length: 194, dtype: str

In [71]:
df['country_long'].apply(check_republic)

0      False
1       True
2       True
3      False
4       True
       ...
189     True
190    False
191     True
192     True
193     True
Name: country_long, Length: 194, dtype: bool

In [72]:
df[df['country_long'].apply(check_republic)]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Vanuatu,Republic of Vanuatu,Vanuatu vatu,Port Vila,Melanesia,Oceania,Ni-Vanuatu,-16.000000,167.000000,1870.0,...,326740,1.92308,242389,84351,0.00,0.00,Unknown,15.6,Charlot Salwai,Prime Minister
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [73]:
df[df['country_long'].apply(check_republic)].count()

country             125
country_long        125
currency            125
capital_city        125
region              125
                   ...
democracy_score     125
democracy_type      125
median_age          125
political_leader    122
title               122
Length: 64, dtype: int64

### Finding the country in African region with maximum population

In [74]:
df['region'].value_counts()

region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [75]:
df['region']=="Eastern Africa"

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190    False
191    False
192     True
193     True
Name: region, Length: 194, dtype: bool

In [76]:
df[df['region']=="Eastern Africa"]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.2114,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.6667,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.1538,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.0000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.4894,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.4286,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.5430,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.9167,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.0000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.4000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.2500,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.8571,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.7080,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.8557,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.8130,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [77]:
df[df['region']=="Western Africa"]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President

In [79]:
(df['region']=="Eastern Africa")|(df['region']=="Western Africa")

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190    False
191    False
192     True
193     True
Name: region, Length: 194, dtype: bool

In [85]:
df[(df['region']=="Eastern Africa")|(df['region']=="Western Africa")]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [91]:
df[(df['region']=="Eastern Africa")|(df['region']=="Western Africa")].sort_values(by='population',ascending=False)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President

In [96]:
african_df=df[(df['region']=="Eastern Africa")|(df['region']=="Western Africa")].sort_values(by='population',ascending=False)

In [101]:
max_population_africa=african_df.iloc[0]['country']
max_population_africa

'Nigeria'

In [95]:
df[(df['region']=="Eastern Africa")|(df['region']=="Western Africa")]['population'].max()

np.int64(218541212)