In [35]:
import numpy as np
import pandas as pd

In [36]:
df=pd.read_csv(r'anime.csv')

In [37]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [38]:
df.shape

(50, 3)

### Feature Extraction

In [39]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [40]:
def extract_episodes(txt):
    extract=False
    episode=""
    for i in txt:
        if i == ")":
            extract=False
            return episode
        if extract:
            episode+=i
        if i=="(":
            extract=True

In [41]:
df['Title'].apply(extract_episodes)

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: str

In [42]:
df['Episodes']=df['Title'].apply(extract_episodes)

In [43]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04   51 eps
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04    1 eps
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04  148 eps
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04   13 eps
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03   13 eps
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03    2 eps
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02  110 eps
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99   13 eps
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99   13 eps
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98   12 eps
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94  201 eps
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94    1 eps
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93   22 eps
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93   24 eps
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91   25 eps
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91    1 eps
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89    1 eps
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88    7 eps
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88   14 eps
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87   74 eps
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84    1 eps
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84    1 eps
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83   12 eps
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83    1 eps
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82   24 eps
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82   23 eps
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81   12 eps
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81   26 eps
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80   13 eps
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80   16 eps
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79   11 eps
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79    1 eps
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79   11 eps
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78   10 eps
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78    1 eps
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77   26 eps
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77   12 eps
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76   75 eps
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75   26 eps
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75   26 eps
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74   24 eps
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73   10 eps
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72   12 eps
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71   12 eps
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71    4 eps

In [44]:
df['Episodes'].str.replace(" eps","").astype(int)

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Episodes, dtype: int64

In [45]:
df['Episodes']=df['Episodes'].str.replace(" eps","").astype(int)

In [46]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      50 non-null     int64
 1   Title     50 non-null     str
 2   Score     50 non-null     float64
 3   Episodes  50 non-null     int64
dtypes: float64(1), int64(2), str(1)
memory usage: 1.7 KB

In [48]:
df['Title']

0     Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1     Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2     Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3     Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4     Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
5     Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...
6     Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...
7     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...
8     Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...
9     Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...
10    Shingeki no Kyojin: The Final Season - Kankets...
11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
12    Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...
13    Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...
14    Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...
15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
16    Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...
17    3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...
18    Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...
19    Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...
20    Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...
21    Violet Evergarden MovieMovie (1 eps)Sep 2020 -...
22    Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...
23    Gintama.: Shirogane no Tamashii-hen - Kouhan-s...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
25    Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...
26    Kaguya-sama wa Kokurasetai: First Kiss wa Owar...
27    Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...
28    The First Slam DunkMovie (1 eps)Dec 2022 - Dec...
29    Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...
30    Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...
31    Gintama.: Shirogane no Tamashii-henTV (12 eps)...
32    Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...
33    Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...
34    Shingeki no Kyojin: The Final SeasonTV (16 eps...
35    Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...
36    Kizumonogatari III: Reiketsu-henMovie (1 eps)J...
37    "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...
38    Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...
39    Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...
40    Monogatari Series: Second SeasonTV (26 eps)Jul...
41    Shingeki no Kyojin: The Final Season Part 2TV ...
42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
43    Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...
44    Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...
45    Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...
46    Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...
47    Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...
48    Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...
49    Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
Name: Title, dtype: str

In [49]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [50]:
df.loc[0].Title

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [51]:
def extract_timestamp(txt):
    time_stamp=""
    for i in range(len(txt)):
        if txt[i]==")":
            for j in range(i+1,i+18):
                time_stamp+=txt[j]
                
            return time_stamp

In [52]:
df['Title'].apply(extract_timestamp)

0     Apr 2009 - Jul 20
1     Apr 2011 - Sep 20
2     Oct 2022 - Dec 20
3     Apr 2015 - Mar 20
4     Apr 2019 - Jul 20
5     Apr 2011 - Mar 20
6     Jan 2021 - Jan 20
7     Oct 2011 - Sep 20
8     Apr 2022 - Jun 20
9     Oct 2012 - Mar 20
10    Mar 2023 - May 20
11    Jan 1988 - Mar 19
12    Jul 2023 - Aug 20
13    Apr 2021 - Jun 20
14    Jan 2017 - Mar 20
15    Apr 2006 - Mar 20
16    Sep 2016 - Sep 20
17    Oct 2017 - Mar 20
18    Oct 2008 - Mar 20
19    Apr 2008 - Sep 20
20    Jul 2013 - Jul 20
21    Sep 2020 - Sep 20
22    Aug 2017 - Aug 20
23    Jul 2018 - Oct 20
24    Apr 2004 - Sep 20
25    Aug 2016 - Aug 20
26    Dec 2022 - Dec 20
27    Oct 2022 - Dec 20
28    Dec 2022 - Dec 20
29    Jan 2023 - Jun 20
30    Jul 2023 - Aug 20
31    Jan 2018 - Mar 20
32    Apr 2020 - Oct 20
33    Jan 2019 - Apr 20
34    Dec 2020 - Mar 20
35    Dec 2021 - Feb 20
36    Jan 2017 - Jan 20
37    Apr 2023 - Jun 20
38    Oct 2016 - Dec 20
39    Jul 2001 - Jul 20
40    Jul 2013 - Dec 20
41    Jan 2022 - Apr 20
42    Oct 2000 - Mar 20
43    Apr 1998 - Apr 19
44    Apr 2022 - Oct 20
45    Jul 2019 - Dec 20
46    Oct 2014 - Dec 20
47    Jan 2017 - Mar 20
48    Oct 2022 - Dec 20
49    Feb 1999 - Sep 19
Name: Title, dtype: str

In [53]:
df['Timeframe']=df['Title'].apply(extract_timestamp)

In [54]:
df.head(3)

,Rank,Title,Score,Episodes,Timeframe
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 20
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 20
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 20

In [55]:
df['Score']

0     9.10
1     9.07
2     9.06
3     9.06
4     9.05
5     9.04
6     9.04
7     9.04
8     9.04
9     9.03
10    9.03
11    9.02
12    8.99
13    8.99
14    8.98
15    8.94
16    8.94
17    8.93
18    8.93
19    8.91
20    8.91
21    8.89
22    8.88
23    8.88
24    8.87
25    8.84
26    8.84
27    8.83
28    8.83
29    8.82
30    8.82
31    8.81
32    8.81
33    8.80
34    8.80
35    8.79
36    8.79
37    8.79
38    8.78
39    8.78
40    8.77
41    8.77
42    8.76
43    8.75
44    8.75
45    8.74
46    8.73
47    8.72
48    8.71
49    8.71
Name: Score, dtype: float64

In [56]:
df['Score'].max()

np.float64(9.1)

In [57]:
highest_score=df['Score'].max()

In [58]:
highest_score

np.float64(9.1)

In [59]:
df['Score']==highest_score

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Score, dtype: bool

In [60]:
df[df['Score']==highest_score]

,Rank,Title,Score,Episodes,Timeframe
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 20

In [61]:
df['Score'].value_counts().sort_values(ascending=False).head(5)

Score
9.04    4
8.79    3
9.06    2
9.03    2
8.99    2
Name: count, dtype: int64

In [62]:
max_episodes=df['Episodes'].max()
max_episodes

np.int64(201)

In [63]:
df[df['Episodes']==max_episodes]

,Rank,Title,Score,Episodes,Timeframe
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 20

In [64]:
df['Score'].unique

<bound method Series.unique of 0     9.10
1     9.07
2     9.06
3     9.06
4     9.05
5     9.04
6     9.04
7     9.04
8     9.04
9     9.03
10    9.03
11    9.02
12    8.99
13    8.99
14    8.98
15    8.94
16    8.94
17    8.93
18    8.93
19    8.91
20    8.91
21    8.89
22    8.88
23    8.88
24    8.87
25    8.84
26    8.84
27    8.83
28    8.83
29    8.82
30    8.82
31    8.81
32    8.81
33    8.80
34    8.80
35    8.79
36    8.79
37    8.79
38    8.78
39    8.78
40    8.77
41    8.77
42    8.76
43    8.75
44    8.75
45    8.74
46    8.73
47    8.72
48    8.71
49    8.71
Name: Score, dtype: float64>

In [65]:
df.head(5)

,Rank,Title,Score,Episodes,Timeframe
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 20
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 20
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 20
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 20
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 20

In [66]:
df['Score'].head(5)

0    9.10
1    9.07
2    9.06
3    9.06
4    9.05
Name: Score, dtype: float64