In [ ]:
import numpy as np
import pandas as pd

### Creating Dataframe from dictionary and Array

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [ ]:
# in case of dictionary, the key acts as the column names
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#in case of array, column names have to be explicitly mentioned
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [ ]:
pd.DataFrame(data_list)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
# specifying explicit column names in case of list
columns=["Name","Age","City","Salary"]
pd.DataFrame(data_list,columns=columns)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# storing dataframe in 'df' variable
df=pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and indexing of columns

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Targeting and selecting a single column and also multiple columns

In [ ]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [ ]:
# for multiple columns, they have to be wrapped inside a list and then passed
df[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating new column

In [ ]:
df['Designation']=["Engineer","Doctor","Engineer","Doctor"]
#here, designation is the column name and the values inside the list appear in the column. each value in a row

In [ ]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

#### Removing Columns

In [ ]:
# by default axis =0, (rows), we have to change it to 1 to delete all the values from the column
df.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# we can notice that the designation is not dropped, but just the copy was shown in the above result
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000      Doctor
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [ ]:
# by using inplace, permanent changes take place in the dataframe
df.drop('Designation',axis=1,inplace=True)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Removing first row by selecting index and setting axis=0

In [ ]:
df.drop(0,axis=0)
# axis 0 targets the rows

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting Rows

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df.loc[0:1]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting particular fields from specific rows

In [ ]:
df.loc[0:1][["Salary","City"]]
#df.loc returns the 0th and the 1st row
# since we are targeting two columns, they are wrapped inside a list and passed

   Salary      City
0   65000  New York
1   70000     Paris

In [ ]:
df.loc[2:3][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

##### Conditional Selection

In [ ]:
# Selecting people whose age is greater than 30 -> 
df['Age']>30

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [ ]:
df[df['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
# Select people with age greater than 30 and city is Paris
(df['Age']>30)& (df['City']=="Paris")

0    False
1     True
2    False
3    False
dtype: bool

In [ ]:
df[(df['Age']>30)& (df['City']=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000