In [23]:
import numpy as np
import pandas as pd

In [24]:
python_list=[1,2,3,4,5]
series=pd.Series(python_list)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [25]:
dictionary={"Baman":65,"Rahul":52,"Chinmay":89}
series=pd.Series(dictionary)
print(series)

Baman      65
Rahul      52
Chinmay    89
dtype: int64

In [26]:
df=pd.DataFrame({
    "name":["Rohit","Virat"],
    "runs":[264,183]
})

print(df)

    name  runs
0  Rohit   264
1  Virat   183

In [27]:
try:
    df=pd.read_csv("employees_100.csv")
except FileNotFoundError:
    print("you've entered wrong file path! try again")
else:
    print(df)

    employee_id            name    department       city   age salary  \
0           184    Swati Kapoor  Data Science    Kolkata  38.0  70719
1           154  Kavya Malhotra   engineering     Mumbai   NaN  77058
2           171    Manish Desai  Data Science  Hyderabad  23.0  69911
3           146        Neha Das   Engineering       Pune  28.0  69993
4           145       Isha Nair  Data Science        NaN  32.0  88216
..          ...             ...           ...        ...   ...    ...
95          161     Nikhil Nair     MARKETING    Chennai  22.0  55740
96          172      Neha Desai            HR    Chennai  22.0  52250
97          115      Neha Reddy     Marketing    Chennai  43.0    NaN
98          193     Priya Nayak            HR        NaN  23.0  56821
99          152     Kavya Joshi     Marketing      Delhi  44.0  69499

    experience  performance_score  projects_completed joining_date
0            5                  5                   6   2021-07-02
1            1                  8                   8   2024-02-05
2            0                  6                  18   2019-04-24
3            3                  8                   1   2022-12-13
4            8                  8                  14   2019-11-25
..         ...                ...                 ...          ...
95           0                  5                  22   2020-04-22
96           0                  5                   7   2020-11-14
97          12                  4                  10   2019-06-06
98           3                  9                  16   2019-08-07
99          10                  7                   4   2022-03-25

[100 rows x 10 columns]

In [28]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [29]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [30]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27

In [31]:
df.shape

(100, 10)

In [32]:
df.dtypes

employee_id             int64
name                      str
department                str
city                      str
age                   float64
salary                    str
experience              int64
performance_score       int64
projects_completed      int64
joining_date              str
dtype: object

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [34]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [35]:
df.isnull()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,True,False,False,False,False
98,False,False,False,True,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False

In [36]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [37]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: str

In [38]:
df[['name','city']]

              name       city
0     Swati Kapoor    Kolkata
1   Kavya Malhotra     Mumbai
2     Manish Desai  Hyderabad
3         Neha Das       Pune
4        Isha Nair        NaN
..             ...        ...
95     Nikhil Nair    Chennai
96      Neha Desai    Chennai
97      Neha Reddy    Chennai
98     Priya Nayak        NaN
99     Kavya Joshi      Delhi

[100 rows x 2 columns]

In [39]:
df[['name','city']].head()

             name       city
0    Swati Kapoor    Kolkata
1  Kavya Malhotra     Mumbai
2    Manish Desai  Hyderabad
3        Neha Das       Pune
4       Isha Nair        NaN

In [40]:
#df=df.set_index("employee_id") # this line was commented after execution
print(df)

    employee_id            name    department       city   age salary  \
0           184    Swati Kapoor  Data Science    Kolkata  38.0  70719
1           154  Kavya Malhotra   engineering     Mumbai   NaN  77058
2           171    Manish Desai  Data Science  Hyderabad  23.0  69911
3           146        Neha Das   Engineering       Pune  28.0  69993
4           145       Isha Nair  Data Science        NaN  32.0  88216
..          ...             ...           ...        ...   ...    ...
95          161     Nikhil Nair     MARKETING    Chennai  22.0  55740
96          172      Neha Desai            HR    Chennai  22.0  52250
97          115      Neha Reddy     Marketing    Chennai  43.0    NaN
98          193     Priya Nayak            HR        NaN  23.0  56821
99          152     Kavya Joshi     Marketing      Delhi  44.0  69499

    experience  performance_score  projects_completed joining_date
0            5                  5                   6   2021-07-02
1            1                  8                   8   2024-02-05
2            0                  6                  18   2019-04-24
3            3                  8                   1   2022-12-13
4            8                  8                  14   2019-11-25
..         ...                ...                 ...          ...
95           0                  5                  22   2020-04-22
96           0                  5                   7   2020-11-14
97          12                  4                  10   2019-06-06
98           3                  9                  16   2019-08-07
99          10                  7                   4   2022-03-25

[100 rows x 10 columns]

In [41]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [42]:
df.loc[0]

employee_id                    184
name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 0, dtype: object

In [43]:
df.loc[184:145]

Empty DataFrame
Columns: [employee_id, name, department, city, age, salary, experience, performance_score, projects_completed, joining_date]
Index: []

In [44]:
df.iloc[0]

employee_id                    184
name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 0, dtype: object

In [45]:
df.iloc[0:10]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
7,181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
8,111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
9,101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [46]:
df.loc[154:145][["name","city","age","salary"]]

Empty DataFrame
Columns: [name, city, age, salary]
Index: []

In [47]:
df.iloc[1:5][["name","city","age","salary"]]

             name       city   age salary
1  Kavya Malhotra     Mumbai   NaN  77058
2    Manish Desai  Hyderabad  23.0  69911
3        Neha Das       Pune  28.0  69993
4       Isha Nair        NaN  32.0  88216

In [48]:
df['age']>25

0      True
1     False
2     False
3      True
4      True
      ...
95    False
96    False
97     True
98    False
99     True
Name: age, Length: 100, dtype: bool

In [49]:
df['projects_completed']>10

0     False
1     False
2      True
3     False
4      True
      ...
95     True
96    False
97    False
98     True
99    False
Name: projects_completed, Length: 100, dtype: bool

In [50]:
df[df['projects_completed']>10]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
10,119,Ritu Desai,Marketing,Pune,22.0,55321,0,6,18,2020-02-18
11,131,Priya Malhotra,Marketing,Hyderabad,25.0,55295,1,7,12,2022-02-13
12,174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
13,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
14,191,Neha Malhotra,Marketing,Mumbai,29.0,64944,2,10,18,2023-10-05
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
21,189,Anjali Shah,Marketing,Delhi,33.0,56321,6,7,14,2022-08-14
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
26,141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
35,106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
37,166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255,1,8,19,2021-12-05
43,196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08
45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
46,182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
53,139,Rahul Malhotra,Marketing,Hyderabad,23.0,60203,2,6,15,2022-09-17
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
59,190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
63,144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
69,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
72,159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
75,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
77,133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
83,130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
86,122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
90,192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [51]:
df[df['age']>30]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
15,105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
21,189,Anjali Shah,Marketing,Delhi,33.0,56321,6,7,14,2022-08-14
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
30,112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
32,186,Rohan Kapoor,NaN,Pune,36.0,65152,8,7,4,2020-02-15
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
37,166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
42,108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
46,182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
49,114,Isha Das,FINANCE,Chennai,35.0,71889,8,5,2,2019-06-21
50,125,Sneha Bose,Marketing,Mumbai,32.0,56627,7,2,9,2023-07-12
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
56,107,Karan Mehta,HR,Delhi,34.0,55119,8,3,8,2021-07-02
57,165,Isha Das,Marketing,Pune,40.0,57895,6,5,1,2023-08-16
58,137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
63,144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
66,147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
68,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
70,180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
73,149,Sanjay Desai,SALES,Hyderabad,37.0,"62,730",8,7,8,2019-01-23
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
75,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
86,122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
87,103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
89,188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
90,192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
92,187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [52]:
df['department']=="Finance"

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: department, Length: 100, dtype: bool

In [53]:
df[df['department']=="Finance"]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
12,174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
13,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
30,112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
52,118,Rajesh Nair,Finance,Hyderabad,26.0,67464,1,5,9,2019-01-26
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
58,137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
64,151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
69,134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
70,180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
83,130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
85,153,Pooja Das,Finance,Mumbai,27.0,64112,1,4,6,2019-08-25

In [54]:
(df['department']=="Finance") & (df['age']>30)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [55]:
df[(df['department']=="Finance") & (df['age']>30)]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
30,112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
58,137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
70,180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

#### Finding people in either sales or finance department, with experience greater than 5 years and age greater than 30

In [56]:
df[((df['department']=="Finance") | (df['department']=="Marketing")) & ((df['age']>30)&(df['experience']>3))]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
21,189,Anjali Shah,Marketing,Delhi,33.0,56321,6,7,14,2022-08-14
50,125,Sneha Bose,Marketing,Mumbai,32.0,56627,7,2,9,2023-07-12
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
57,165,Isha Das,Marketing,Pune,40.0,57895,6,5,1,2023-08-16
58,137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
79,160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

### Data Cleaning Operations

In [57]:
df.isnull()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,True,False,False,False,False
98,False,False,False,True,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False

In [58]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [59]:
df.dropna()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...,...
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [60]:
df.dropna(subset=['city'])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [61]:
df.dropna(subset=['city','age'])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [62]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [63]:
df['age'].fillna(df['age'].mean())

0     38.000000
1     30.861702
2     23.000000
3     28.000000
4     32.000000
        ...
95    22.000000
96    22.000000
97    43.000000
98    23.000000
99    44.000000
Name: age, Length: 100, dtype: float64

In [64]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [65]:
df['salary']=df['salary'].str.replace(",","",regex=False)
df['salary']=pd.to_numeric(df['salary'],errors='coerce')
df['salary'].fillna(df['salary'].median())

0     70719.0
1     77058.0
2     69911.0
3     69993.0
4     88216.0
       ...
95    55740.0
96    52250.0
97    62969.5
98    56821.0
99    69499.0
Name: salary, Length: 100, dtype: float64

In [66]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [67]:
df['department']=df['department'].fillna(df['department'].mode()[0])

In [68]:
df['city'].value_counts()

city
Hyderabad    19
Pune         14
Delhi        14
Kolkata      13
Mumbai       10
Bangalore    10
Chennai      10
Name: count, dtype: int64

In [69]:
df['city']=df['city'].fillna(df['city'].mode()[0])

In [70]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   6
salary                8
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df=df.reset_index()

In [73]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740.0,0,5,22,2020-04-22
96,96,172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,98,193,Priya Nayak,HR,Hyderabad,23.0,56821.0,3,9,16,2019-08-07
99,99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25

In [74]:
df.duplicated(subset=["employee_id"]).sum()

np.int64(4)

In [75]:
df.drop_duplicates(subset=["employee_id"],keep="first",inplace=True)

In [76]:
df['joining_date']=pd.to_datetime(df['joining_date'])

In [77]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740.0,0,5,22,2020-04-22
96,96,172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,98,193,Priya Nayak,HR,Hyderabad,23.0,56821.0,3,9,16,2019-08-07
99,99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25

### Modifying Data and Creating New Columns

In [78]:
df['annual_salary']=df['salary']*12

In [79]:
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0
1,1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0

In [80]:
def categorize(number):
    if number>5:
        return "Experienced Candidate"
    elif number<=5:
        return "Learner"

In [81]:
df['experience_status']=df['experience'].apply(categorize)

In [82]:
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate

### Sorting and Ranking

In [83]:
df.sort_values(by="salary")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
26,26,141,Manish Kulkarni,HR,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Learner
36,36,167,Meera Malhotra,HR,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Learner
33,33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Learner
67,67,169,Swati Chatterjee,HR,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Learner
7,7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN,Experienced Candidate
45,45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27,NaN,Experienced Candidate
55,55,179,Arjun Das,Finance,Hyderabad,43.0,NaN,10,7,11,2024-08-25,NaN,Experienced Candidate
60,60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07,NaN,Learner
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,Experienced Candidate

In [84]:
df.sort_values(by="salary",ascending=False)

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
74,74,158,Tanvi Malhotra,HR,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced Candidate
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced Candidate
84,84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced Candidate
39,39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN,Experienced Candidate
45,45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27,NaN,Experienced Candidate
55,55,179,Arjun Das,Finance,Hyderabad,43.0,NaN,10,7,11,2024-08-25,NaN,Experienced Candidate
60,60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07,NaN,Learner
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,Experienced Candidate

In [85]:
df['department'].unique()

<StringArray>
['Data Science',  'engineering',  'Engineering',        'Sales',
           'HR',    'Marketing',  ' Marketing ',      'Finance',
    ' Finance ',         ' HR ',      'FINANCE',        'SALES',
    'MARKETING']
Length: 13, dtype: str

In [86]:
df['department']=df['department'].str.strip().str.title()

In [87]:
df['department'].unique()

<StringArray>
['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing', 'Finance']
Length: 6, dtype: str

In [88]:
result=df.sort_values(by=['department','salary'],ascending=[True,False])
result

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced Candidate
59,59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,941580.0,Learner
24,24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Learner
54,54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24,915204.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26,694296.0,Learner
44,44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04,634344.0,Learner
38,38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,630876.0,Learner
5,5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,628848.0,Learner
23,23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN,Experienced Candidate

In [89]:
df['salary_rank']=df['salary'].rank(ascending=False)

In [90]:
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner,26.0
1,1,154,Kavya Malhotra,Engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner,13.0
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner,28.0
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner,27.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate,2.0

In [91]:
df.sort_values(by="salary_rank")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
74,74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced Candidate,1.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate,2.0
88,88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced Candidate,3.0
84,84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced Candidate,4.0
39,39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN,Experienced Candidate,NaN
45,45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27,NaN,Experienced Candidate,NaN
55,55,179,Arjun Das,Finance,Hyderabad,43.0,NaN,10,7,11,2024-08-25,NaN,Experienced Candidate,NaN
60,60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07,NaN,Learner,NaN
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,Experienced Candidate,NaN

In [92]:
df.nlargest(5,"age")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
62,62,155,Sanjay Das,Hr,Bangalore,45.0,74505.0,17,6,10,2022-06-22,894060.0,Experienced Candidate,22.0
99,99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25,833988.0,Experienced Candidate,30.0
55,55,179,Arjun Das,Finance,Hyderabad,43.0,NaN,10,7,11,2024-08-25,NaN,Experienced Candidate,NaN
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,Experienced Candidate,NaN
61,61,164,Sneha Gupta,Hr,Delhi,42.0,63209.0,11,3,8,2021-08-07,758508.0,Experienced Candidate,44.0

In [93]:
df.nsmallest(5,"performance_score")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
20,20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765.0,0,2,4,2020-04-12,837180.0,Learner,29.0
24,24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Learner,14.0
50,50,125,Sneha Bose,Marketing,Mumbai,32.0,56627.0,7,2,9,2023-07-12,679524.0,Experienced Candidate,69.0
76,76,176,Shreya Menon,Finance,Hyderabad,41.0,80597.0,9,2,18,2024-11-09,967164.0,Experienced Candidate,7.0
12,12,174,Divya Chatterjee,Finance,Kolkata,24.0,58374.0,1,3,12,2018-09-21,700488.0,Learner,63.0

### Grouping and Aggregation

In [94]:
df['city'].unique()

<StringArray>
['Kolkata', 'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Bangalore', 'Chennai']
Length: 7, dtype: str

In [95]:
df['city'].nunique()

7

In [96]:
df

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner,26.0
1,1,154,Kavya Malhotra,Engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner,13.0
2,2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner,28.0
3,3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner,27.0
4,4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,Marketing,Chennai,22.0,55740.0,0,5,22,2020-04-22,668880.0,Learner,74.0
96,96,172,Neha Desai,Hr,Chennai,22.0,52250.0,0,5,7,2020-11-14,627000.0,Learner,82.0
97,97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,Experienced Candidate,NaN
98,98,193,Priya Nayak,Hr,Hyderabad,23.0,56821.0,3,9,16,2019-08-07,681852.0,Learner,68.0
99,99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25,833988.0,Experienced Candidate,30.0

In [97]:
df.groupby('city')

In [98]:
df.groupby('city')['age'].mean()

city
Bangalore    34.375000
Chennai      29.250000
Delhi        33.250000
Hyderabad    30.892857
Kolkata      28.000000
Mumbai       27.375000
Pune         31.642857
Name: age, dtype: float64

In [99]:
df.groupby('city')['salary'].max()

city
Bangalore    81112.0
Chennai      77222.0
Delhi        80358.0
Hyderabad    88216.0
Kolkata      84255.0
Mumbai       88366.0
Pune         78545.0
Name: salary, dtype: float64

In [100]:
df.info()

<class 'pandas.DataFrame'>
Index: 96 entries, 0 to 99
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               96 non-null     int64
 1   employee_id         96 non-null     int64
 2   name                96 non-null     str
 3   department          96 non-null     str
 4   city                96 non-null     str
 5   age                 90 non-null     float64
 6   salary              88 non-null     float64
 7   experience          96 non-null     int64
 8   performance_score   96 non-null     int64
 9   projects_completed  96 non-null     int64
 10  joining_date        96 non-null     datetime64[us]
 11  annual_salary       88 non-null     float64
 12  experience_status   96 non-null     str
 13  salary_rank         88 non-null     float64
dtypes: datetime64[us](1), float64(4), int64(5), str(4)
memory usage: 11.2 KB

In [101]:
df.sample()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
31,31,148,Kavya Nair,Engineering,Chennai,NaN,76320.0,3,7,11,2024-03-07,915840.0,Learner,15.0